spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:server}?stringtype=unspecified
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
  docker:
    compose:
      file: "./server/compose.yml"
      enabled: false
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /v3/api-docs/openapi.json
