[versions]
kotlionVersion = "1.9.23"
junitVersion = "5.7.2"

[libraries]
# Plugins that are used in buildLogic
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlionVersion" }
ktfmtPlugin = { module = "com.ncorti.ktfmt.gradle:plugin", version = "0.18.0" }
testLoggerPlugin = { module = "com.adarshr:gradle-test-logger-plugin", version = "4.0.0" }


# Kotlin related
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version = "6.0.9" }
ztExec = { module = "org.zeroturnaround:zt-exec", version = "1.12" }

# Testing related
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
assertJCore = { module = "org.assertj:assertj-core", version = "3.21.0" }

[bundles]
junit = ["junitApi", "junitEngine", "assertJCore"]