[versions]
kotlionVersion = "1.9.22"

[libraries]
# Plugins that are used in buildLogic
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlionVersion" }
ktfmtPlugin = { module = "com.ncorti.ktfmt.gradle:plugin", version = "0.17.0" }
testLoggerPlugin = { module = "com.adarshr:gradle-test-logger-plugin", version = "4.0.0" }


# Kotlin related
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version = "6.0.3" }



